trigger:
  branches:
    include:
      - master
  paths:
    include:
      - './server/*'
pool:
  vmImage: 'ubuntu-latest'
steps:
- task: DotNetCoreCLI@2
  displayName: .Net Core Restore
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: .Net Core Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration Release'
- task: DotNetCoreCLI@2
  displayName: .Net Core Publish
  inputs:
    command: publish
    publishWebProjects: false
    projects: '**/*.csproj'
    arguments: --output $(Build.ArtifactStagingDirectory)
    zipAfterPublish: false
- task: PublishBuildArtifacts@1
  displayName: Artifacts Publish
- task: Docker@2
  displayName: Login to Docker Hub
  inputs:
    containerRegistry: 'docker-hub-connection'
    command: 'login'
- task: Docker@2
  displayName: Build and Push
  inputs:
    containerRegistry: 'docker-hub-connection'
    repository: 'vesper0990/wordki-server'
    command: 'buildAndPush'
    Dockerfile: 'server/src/Wordki.Api/Dockerfile.Production'
    buildContext: 'server/src/'
    tags: |
      $(Build.BuildId)
      latest