trigger:
  branches:
    include:
      - master
  paths:
    include:
      - 'server/*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DockerCompose@0
  displayName: Build
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'docker-hub-connection'
    dockerComposeFile: 'server/build/docker/docker-compose.build.yml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: up
- task: DockerCompose@0
  displayName: Run Tests
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'docker-hub-connection'
    dockerComposeFile: 'server/build/docker/docker-compose.test.yml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: up
- task: CmdLine@2
  displayName: Copy test results
  inputs:
    script: |
      docker ps -a
      docker cp wordki-server.ci.e2e:/server/tests/Wordki.Tests.E2E/TestResults $(System.DefaultWorkingDirectory)/test
      ls $(System.DefaultWorkingDirectory)/test
- task: PublishTestResults@2
  displayName: Publish test results
  inputs:
    testResultsFormat: 'JUnit'
    searchFolder: $(System.DefaultWorkingDirectory)/test
    testResultsFiles: '*.xml'
- task: DockerCompose@0
  displayName: Release
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'docker-hub-connection'
    dockerComposeFile: 'server/build/docker/docker-compose.release.yml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: build
- task: Docker@2
  displayName: Login to Docker Hub
  inputs:
    containerRegistry: 'docker-hub-connection'
    command: 'login'
- task: Docker@2
  displayName: Push
  inputs:
    containerRegistry: 'docker-hub-connection'
    repository: 'vesper0990/wordki-server'
    command: 'push'
    tags: |
      $(Build.BuildId)